"""Phase 3 performance database indexes

Revision ID: 1688b12d91cb
Revises: 66cd6fb13108
Create Date: 2026-09-06 15:33:00.237947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1688b12d91cb'
down_revision: Union[str, None] = '66cd6fb13108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ai_insights_product_id'), 'ai_insights', ['product_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_cash_closings_cashier_id'), 'cash_closings', ['cashier_id'], unique=False)
    op.create_index(op.f('ix_inventory_closing_items_inventory_closing_id'), 'inventory_closing_items', ['inventory_closing_id'], unique=False)
    op.create_index(op.f('ix_inventory_closing_items_product_id'), 'inventory_closing_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_actor_id'), 'inventory_movements', ['actor_id'], unique=False)
    op.create_index('ix_inventory_movements_prod_type', 'inventory_movements', ['product_id', 'movement_type'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_reference', 'notifications', ['reference_type', 'reference_id'], unique=False)
    op.create_index(op.f('ix_notifications_target_user_id'), 'notifications', ['target_user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['target_user_id', 'is_read', 'created_at'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_receiving_items_product_id'), 'receiving_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_receiving_items_receiving_id'), 'receiving_items', ['receiving_id'], unique=False)
    op.create_index(op.f('ix_receivings_reviewed_by_id'), 'receivings', ['reviewed_by_id'], unique=False)
    op.create_index(op.f('ix_receivings_submitted_by_id'), 'receivings', ['submitted_by_id'], unique=False)
    op.create_index(op.f('ix_receivings_supplier_id'), 'receivings', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_sale_items_product_id'), 'sale_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    op.create_index(op.f('ix_sales_cashier_id'), 'sales', ['cashier_id'], unique=False)
    op.create_index('ix_sales_date_cashier', 'sales', ['business_date', 'cashier_id'], unique=False)
    op.create_index(op.f('ix_stock_opname_items_product_id'), 'stock_opname_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_opname_items_stock_opname_id'), 'stock_opname_items', ['stock_opname_id'], unique=False)
    op.create_index(op.f('ix_stock_opnames_reviewed_by_id'), 'stock_opnames', ['reviewed_by_id'], unique=False)
    op.create_index(op.f('ix_stock_opnames_started_by_id'), 'stock_opnames', ['started_by_id'], unique=False)
    op.create_index(op.f('ix_supplier_products_product_id'), 'supplier_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_supplier_products_supplier_id'), 'supplier_products', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_warehouse_requests_product_id'), 'warehouse_requests', ['product_id'], unique=False)
    op.create_index(op.f('ix_warehouse_requests_requested_by_id'), 'warehouse_requests', ['requested_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouse_requests_requested_by_id'), table_name='warehouse_requests')
    op.drop_index(op.f('ix_warehouse_requests_product_id'), table_name='warehouse_requests')
    op.drop_index(op.f('ix_supplier_products_supplier_id'), table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_product_id'), table_name='supplier_products')
    op.drop_index(op.f('ix_stock_opnames_started_by_id'), table_name='stock_opnames')
    op.drop_index(op.f('ix_stock_opnames_reviewed_by_id'), table_name='stock_opnames')
    op.drop_index(op.f('ix_stock_opname_items_stock_opname_id'), table_name='stock_opname_items')
    op.drop_index(op.f('ix_stock_opname_items_product_id'), table_name='stock_opname_items')
    op.drop_index('ix_sales_date_cashier', table_name='sales')
    op.drop_index(op.f('ix_sales_cashier_id'), table_name='sales')
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_product_id'), table_name='sale_items')
    op.drop_index(op.f('ix_receivings_supplier_id'), table_name='receivings')
    op.drop_index(op.f('ix_receivings_submitted_by_id'), table_name='receivings')
    op.drop_index(op.f('ix_receivings_reviewed_by_id'), table_name='receivings')
    op.drop_index(op.f('ix_receiving_items_receiving_id'), table_name='receiving_items')
    op.drop_index(op.f('ix_receiving_items_product_id'), table_name='receiving_items')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_target_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_reference', table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('ix_inventory_movements_prod_type', table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_actor_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_closing_items_product_id'), table_name='inventory_closing_items')
    op.drop_index(op.f('ix_inventory_closing_items_inventory_closing_id'), table_name='inventory_closing_items')
    op.drop_index(op.f('ix_cash_closings_cashier_id'), table_name='cash_closings')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_ai_insights_product_id'), table_name='ai_insights')
    # ### end Alembic commands ###
