"""Refactor models for opname items closing items rbac and cash adjustments

Revision ID: e788108c2d21
Revises: 0d71e6ab3d8a
Create Date: 2026-09-06 15:09:14.392329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision: str = 'e788108c2d21'
down_revision: Union[str, None] = '0d71e6ab3d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE sale_status_enum ADD VALUE IF NOT EXISTS 'PARTIALLY_REFUNDED'")
    op.create_table('permissions',

    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('stock_opname_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_opname_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('system_display_quantity', sa.Integer(), nullable=False),
    sa.Column('system_on_hand_quantity', sa.Integer(), nullable=False),
    sa.Column('physical_display_quantity', sa.Integer(), nullable=False),
    sa.Column('physical_on_hand_quantity', sa.Integer(), nullable=False),
    sa.Column('display_variance', sa.Integer(), nullable=False),
    sa.Column('on_hand_variance', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('MATCHED', 'VARIANCE_DETECTED', 'ADJUSTED', name='stock_opname_item_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['stock_opname_id'], ['stock_opnames.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_closing_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_closing_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('opening_display_quantity', sa.Integer(), nullable=False),
    sa.Column('opening_on_hand_quantity', sa.Integer(), nullable=False),
    sa.Column('receiving_quantity', sa.Integer(), nullable=False),
    sa.Column('sales_quantity', sa.Integer(), nullable=False),
    sa.Column('adjustment_quantity', sa.Integer(), nullable=False),
    sa.Column('return_quantity', sa.Integer(), nullable=False),
    sa.Column('other_movement_quantity', sa.Integer(), nullable=False),
    sa.Column('expected_display_quantity', sa.Integer(), nullable=False),
    sa.Column('expected_on_hand_quantity', sa.Integer(), nullable=False),
    sa.Column('physical_display_quantity', sa.Integer(), nullable=False),
    sa.Column('physical_on_hand_quantity', sa.Integer(), nullable=False),
    sa.Column('display_variance', sa.Integer(), nullable=False),
    sa.Column('on_hand_variance', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('MATCHED', 'NEEDS_REVIEW', 'ADJUSTED', 'RESOLVED', name='inventory_closing_variance_status_enum', create_type=False), nullable=False),


    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inventory_closing_id'], ['inventory_closings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cash_closings', sa.Column('cash_adjustment', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('cash_closings', sa.Column('adjustment_notes', sa.Text(), nullable=True))
    op.add_column('inventory_closings', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('inventory_closings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint(op.f('inventory_closings_product_id_fkey'), 'inventory_closings', type_='foreignkey')
    op.drop_column('inventory_closings', 'product_id')
    op.drop_column('inventory_closings', 'physical_on_hand')
    op.drop_column('inventory_closings', 'opening_stock')
    op.drop_column('inventory_closings', 'variance')
    op.drop_column('inventory_closings', 'expected_stock')
    op.drop_column('inventory_closings', 'physical_display')
    op.add_column('users', sa.Column('role_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.add_column('inventory_closings', sa.Column('physical_display', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('inventory_closings', sa.Column('expected_stock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('inventory_closings', sa.Column('variance', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('inventory_closings', sa.Column('opening_stock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('inventory_closings', sa.Column('physical_on_hand', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('inventory_closings', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('inventory_closings_product_id_fkey'), 'inventory_closings', 'products', ['product_id'], ['id'])
    op.drop_column('inventory_closings', 'updated_at')
    op.drop_column('inventory_closings', 'notes')
    op.drop_column('cash_closings', 'adjustment_notes')
    op.drop_column('cash_closings', 'cash_adjustment')
    op.drop_table('inventory_closing_items')
    op.drop_table('stock_opname_items')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
