"""events_google_calendar_integration

Revision ID: 023918d98d24
Revises: b3d17a432cd5
Create Date: 2026-09-16 18:32:23.597825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '023918d98d24'
down_revision: Union[str, None] = 'b3d17a432cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('google_event_id', sa.String(length=255), nullable=True, comment='Google Calendar event ID for upsert deduplication'))
    op.add_column('events', sa.Column('location', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_events_google_event_id'), 'events', ['google_event_id'], unique=True)
    op.drop_column('events', 'impact_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('impact_level', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='event_impact_level_enum'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_events_google_event_id'), table_name='events')
    op.drop_column('events', 'location')
    op.drop_column('events', 'google_event_id')
    # ### end Alembic commands ###
