"""phase_5_ai_hermes_notifications

Revision ID: b3d17a432cd5
Revises: 6a21e679c253
Create Date: 2026-09-07 22:02:12.922551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3d17a432cd5'
down_revision: Union[str, None] = '6a21e679c253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    insight_category_enum = postgresql.ENUM('DEMAND', 'RISK', 'ANOMALY', 'REORDER', name='insight_category_enum')
    insight_category_enum.create(op.get_bind(), checkfirst=True)

    insight_severity_enum = postgresql.ENUM('INFO', 'WARNING', 'CRITICAL', name='insight_severity_enum')
    insight_severity_enum.create(op.get_bind(), checkfirst=True)

    insight_status_enum = postgresql.ENUM('ACTIVE', 'DISMISSED', 'RESOLVED', name='insight_status_enum')
    insight_status_enum.create(op.get_bind(), checkfirst=True)

    risk_level_enum = postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level_enum')
    risk_level_enum.create(op.get_bind(), checkfirst=True)

    notification_type_enum = postgresql.ENUM('STOCKOUT_RISK', 'REORDER_RECOMMENDATION', 'ANOMALY_ALERT', 'GENERAL', name='notification_type_enum')
    notification_type_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('demand_forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_quantity', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_forecasts_forecast_date'), 'demand_forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_demand_forecasts_product_id'), 'demand_forecasts', ['product_id'], unique=False)
    op.create_table('stockout_risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('daily_burn_rate', sa.Float(), nullable=False),
    sa.Column('current_total_stock', sa.Integer(), nullable=False),
    sa.Column('days_until_stockout', sa.Float(), nullable=False),
    sa.Column('risk_level', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level_enum', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stockout_risk_scores_product_id'), 'stockout_risk_scores', ['product_id'], unique=False)
    op.create_index(op.f('ix_stockout_risk_scores_risk_level'), 'stockout_risk_scores', ['risk_level'], unique=False)
    op.add_column('ai_insights', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('ai_insights', sa.Column('category', postgresql.ENUM('DEMAND', 'RISK', 'ANOMALY', 'REORDER', name='insight_category_enum', create_type=False), nullable=False))
    op.add_column('ai_insights', sa.Column('severity', postgresql.ENUM('INFO', 'WARNING', 'CRITICAL', name='insight_severity_enum', create_type=False), nullable=False))
    op.add_column('ai_insights', sa.Column('action_recommended', sa.Text(), nullable=True))
    op.add_column('ai_insights', sa.Column('insight_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_insights', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_ai_insights_insight_type'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_priority'), table_name='ai_insights')
    op.create_index(op.f('ix_ai_insights_category'), 'ai_insights', ['category'], unique=False)
    op.create_index(op.f('ix_ai_insights_severity'), 'ai_insights', ['severity'], unique=False)
    op.create_index(op.f('ix_ai_insights_status'), 'ai_insights', ['status'], unique=False)
    op.drop_column('ai_insights', 'priority')
    op.drop_column('ai_insights', 'summary')
    op.drop_column('ai_insights', 'recommendation')
    op.drop_column('ai_insights', 'evidence_data')
    op.drop_column('ai_insights', 'insight_type')
    op.add_column('notifications', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('type', postgresql.ENUM('STOCKOUT_RISK', 'REORDER_RECOMMENDATION', 'ANOMALY_ALERT', 'GENERAL', name='notification_type_enum', create_type=False), nullable=False))
    op.add_column('notifications', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_reference'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_target_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_unread'), table_name='notifications')
    op.create_index(op.f('ix_notifications_target_role'), 'notifications', ['target_role'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_constraint(op.f('notifications_target_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notifications', 'notification_type')
    op.drop_column('notifications', 'reference_id')
    op.drop_column('notifications', 'reference_type')
    op.drop_column('notifications', 'target_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
