"""Add PeriodicAnalysis table

Revision ID: fe913444f158
Revises: 18e190f5840b
Create Date: 2026-09-16 19:41:44.154091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe913444f158'
down_revision: Union[str, None] = '18e190f5840b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodic_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.Enum('WEEKLY', 'MONTHLY', name='analysisperiod'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Summary of the raw data used for the analysis'),
    sa.Column('analysis_result', sa.Text(), nullable=False, comment='The markdown narrative generated by the AI agent'),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periodic_analysis_period_type'), 'periodic_analysis', ['period_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_periodic_analysis_period_type'), table_name='periodic_analysis')
    op.drop_table('periodic_analysis')
    # ### end Alembic commands ###
