"""add_is_analyzed_to_events

Revision ID: 18e190f5840b
Revises: 023918d98d24
Create Date: 2026-09-16 19:08:06.611191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e190f5840b'
down_revision: Union[str, None] = '023918d98d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_analyzed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_analyzed')
    # ### end Alembic commands ###
