"""Phase 4 business semantics refund models and ai insight lifecycle

Revision ID: 6a21e679c253
Revises: 1688b12d91cb
Create Date: 2026-09-06 15:35:34.801881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a21e679c253'
down_revision: Union[str, None] = '1688b12d91cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE insight_status_enum ADD VALUE IF NOT EXISTS 'GENERATED'")
    op.execute("ALTER TYPE insight_status_enum ADD VALUE IF NOT EXISTS 'REVIEWED'")
    op.create_table('sale_refunds',

    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('refund_number', sa.String(length=50), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('processed_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('refund_amount >= 0', name='ck_sale_refunds_amount_non_negative'),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_refunds_processed_by_id'), 'sale_refunds', ['processed_by_id'], unique=False)
    op.create_index(op.f('ix_sale_refunds_refund_number'), 'sale_refunds', ['refund_number'], unique=True)
    op.create_index(op.f('ix_sale_refunds_sale_id'), 'sale_refunds', ['sale_id'], unique=False)
    op.create_table('sale_refund_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('refund_id', sa.UUID(), nullable=False),
    sa.Column('sale_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_sale_refund_items_qty_positive'),
    sa.CheckConstraint('refund_amount >= 0', name='ck_sale_refund_items_amount_non_negative'),
    sa.ForeignKeyConstraint(['refund_id'], ['sale_refunds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_refund_items_refund_id'), 'sale_refund_items', ['refund_id'], unique=False)
    op.create_index(op.f('ix_sale_refund_items_sale_item_id'), 'sale_refund_items', ['sale_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_refund_items_sale_item_id'), table_name='sale_refund_items')
    op.drop_index(op.f('ix_sale_refund_items_refund_id'), table_name='sale_refund_items')
    op.drop_table('sale_refund_items')
    op.drop_index(op.f('ix_sale_refunds_sale_id'), table_name='sale_refunds')
    op.drop_index(op.f('ix_sale_refunds_refund_number'), table_name='sale_refunds')
    op.drop_index(op.f('ix_sale_refunds_processed_by_id'), table_name='sale_refunds')
    op.drop_table('sale_refunds')
    # ### end Alembic commands ###
