"""Phase 1 structural db improvements

Revision ID: 761924d0aa7e
Revises: e788108c2d21
Create Date: 2026-09-06 15:26:22.484112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '761924d0aa7e'
down_revision: Union[str, None] = 'e788108c2d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_inventory_closing_items_closing_product', 'inventory_closing_items', ['inventory_closing_id', 'product_id'])
    op.create_index(op.f('ix_inventory_closings_daily_closing_id'), 'inventory_closings', ['daily_closing_id'], unique=True)
    op.create_unique_constraint('uq_role_permissions_role_permission', 'role_permissions', ['role_id', 'permission_id'])
    op.create_unique_constraint('uq_stock_opname_items_opname_product', 'stock_opname_items', ['stock_opname_id', 'product_id'])
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('OWNER', 'WAREHOUSE_ADMIN', 'WAREHOUSE_STAFF', 'CASHIER', name='user_role_enum'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_constraint('uq_stock_opname_items_opname_product', 'stock_opname_items', type_='unique')
    op.drop_constraint('uq_role_permissions_role_permission', 'role_permissions', type_='unique')
    op.drop_index(op.f('ix_inventory_closings_daily_closing_id'), table_name='inventory_closings')
    op.drop_constraint('uq_inventory_closing_items_closing_product', 'inventory_closing_items', type_='unique')
    # ### end Alembic commands ###
